services:
  - type: web
    name: django-backend
    env: docker
    plan: free
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    postDeployCommand: |
      python manage.py migrate &&
      python manage.py shell -c "from django.contrib.auth.models import User; \
if not User.objects.filter(username='admin').exists(): \
    User.objects.create_superuser('admin', 'admin@example.com', 'admin123')"
